# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- feature/*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  jobs:
    - template: .azuredevops/templates/build.yml  # Template reference

- stage: Development
  jobs:
  - template: .azuredevops/templates/deployment.yml 
    parameters:
      environment: Development
  
- stage: Test
  jobs:
  - template: .azuredevops/templates/deployment.yml 
    parameters:
      environment: Test
  
- stage: Production
  jobs:
  - template: .azuredevops/templates/deployment.yml 
    parameters:
      environment: Test
